### PR TITLE
Updates for python3 syntax

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR updates the `cigetcert` script to use python3-compatible syntax for `print` and `except`.

### CODE REVIEW

**Comment by DrDaveD** [comment]
Thanks, Duncan, looks good.

**Comment by DrDaveD** [comment]
This is now released in tagged version 1.17.

**Comment by duncanmmacleod** [comment]
@DrDaveD, ok, I'll start posting some PRs. I also think it would be useful to have this as a full python library, mainly to support `pip` installations. I can also put that together if you would be open to it.

**Comment by DrDaveD** [comment]
Sure I would be open to that.

**Pull request merged**
