### PR TITLE
check for clean shutdown

### PR DESCRIPTION
**Pull request by afgao6**

### CODE REVIEW

**Comment by DrDaveD** [comment]
This code doesn't do anything because the check just above it always returns.

If I remove the check above it ends up not reading any data from cigetcertopts.txt.  If I only call close, it works.  According to the [m2crypto source code](https://gitlab.com/m2crypto/m2crypto/blob/master/M2Crypto/SSL/Connection.py#L84) the close function is already calling ssl_shutdown, so maybe we don't need to do anything but call close.

**Comment by afgao6** [comment]
Since the m2crypto close function is calling ssl_shutdown (but not close), would we need to also call __del__ to actually close the socket? Because most people seem to recommend both shutting down and closing a socket..

**Comment by DrDaveD** [comment]
I assume that m2crypto is closing the socket when it received a shutdown reply.  In any case, I don't think it matters because the cigetcert application stops using it and soon exits, which will close all file descriptors.

**Comment by DrDaveD** [comment]
Replaced by #28

**Pull request closed without merging**
